# Generated by Django 3.2.5 on 2021-07-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language'),
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default='English', help_text='Enter a language of the book.', max_length=200),
        ),
    ]
